# SPDX-License-Identifier: Apache-2.0

FROM node:bookworm-slim@sha256:dfb18d8011c0b3a112214a32e772d9c6752131ffee512e974e59367e46fcee52

ARG HC_VERSION="3.4.0"
ARG SC_VERSION="5.2.1"

WORKDIR /app

#
# first install is required for hipcheck
# second install is for OSS-P4/R
#
RUN set -eux \
    && apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates git curl xz-utils \
    && apt-get install --no-install-recommends -y procps bc jq unzip file csvtool \
    && rm -rf /var/lib/apt/lists/* \
    && adduser --disabled-password hc_user \
    && chown -R hc_user /app

USER hc_user
ENV HOME=/home/hc_user 

RUN set -eux \
    && mkdir -p ${HOME}/.local/bin/

#
# installs hipcheck
#
RUN set -eux \
    && curl -sSfL https://github.com/mitre/hipcheck/releases/download/hipcheck-v${HC_VERSION}/hipcheck-x86_64-unknown-linux-gnu.tar.xz -o hipcheck-x86_64-unknown-linux-gnu.tar.xz \
    && curl -sSfL https://github.com/mitre/hipcheck/releases/download/hipcheck-v${HC_VERSION}/hipcheck-x86_64-unknown-linux-gnu.tar.xz.sha256 -o hipcheck-x86_64-unknown-linux-gnu.tar.xz.sha256 \
    && sha256sum -c --strict hipcheck-x86_64-unknown-linux-gnu.tar.xz.sha256 --ignore-missing \
    && tar xf hipcheck-x86_64-unknown-linux-gnu.tar.xz --strip-components 1 -C ${HOME}/.local/bin/ hipcheck-x86_64-unknown-linux-gnu/hc \
    && rm -f hipcheck-x86_64-unknown-linux-gnu.tar.xz hipcheck-x86_64-unknown-linux-gnu.tar.xz.sha256

#
# installs phylum.io CLI (OSS-P4/R)
#
# the phylum script has a openssl verification step
# to confirm the digital signature for said script
#
RUN set -eux \
    && curl https://sh.phylum.io/ | sh -s -- --yes

#
# installs grype (OSS-P4/R)
#
# the grype script uses cosign to verify the script
# TODO: install and get this to pass a cosign/sigstore verification
#
#RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -v -b ${HOME}/.local/bin
RUN set -eux \
    && curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ${HOME}/.local/bin

#
# installs scorecard and criticality_score (OSS-P4/R)
# TODO: track OSSF and use a criticality_score container should it ever occur
#
RUN set -eux \
    && curl -sSfL https://github.com/ossf/scorecard/releases/download/v${SC_VERSION}/scorecard_${SC_VERSION}_linux_amd64.tar.gz -o scorecard_${SC_VERSION}_linux_amd64.tar.gz \
    && curl -sSfL https://github.com/ossf/scorecard/releases/download/v${SC_VERSION}/scorecard_checksums.txt -o scorecard_checksums.txt \
    && sha256sum -c --strict scorecard_checksums.txt --ignore-missing \
    && tar xfz scorecard_${SC_VERSION}_linux_amd64.tar.gz -C ${HOME}/.local/bin/ scorecard \
    && rm -f scorecard_${SC_VERSION}_linux_amd64.tar.gz scorecard_checksums.txt

COPY --chown=hc_user:hc_user --from=cmu-sei/criticality_score:dev /home/nonroot/criticality_score ${HOME}/.local/bin/criticality_score

RUN set -eux \
    && mkdir -p ${HOME}/.local/bin/settings

#
# installs OSS-P4/R scripts and config files
#
COPY --chown=hc_user:hc_user scir-oss.sh ${HOME}/.local/bin/
COPY --chown=hc_user:hc_user pub-scir.sh ${HOME}/.local/bin/
COPY --chown=hc_user:hc_user settings/ ${HOME}/.local/bin/settings/

USER root
RUN chown hc_user:hc_user ${HOME}/.local/bin/settings/scir-oss/localizations.lib.sh
RUN chown -R hc_user:hc_user ${HOME}/.local/bin/settings/

USER hc_user
RUN echo "# added by docker build" >> ${HOME}/.local/bin/settings/scir-oss/localizations.lib.sh \
    && echo "_LOCAL_OSSFCS=${HOME}/.local/bin/criticality_score" >> ${HOME}/.local/bin/settings/scir-oss/localizations.lib.sh \
    && echo "_LOCAL_OSSFSC=${HOME}/.local/bin/scorecard" >> ${HOME}/.local/bin/settings/scir-oss/localizations.lib.sh \
    && echo "_LOCAL_MITRHC=${HOME}/.local/bin/hc" >> ${HOME}/.local/bin/settings/scir-oss/localizations.lib.sh

ENV SCIR_CONTAINER=true
ENV PATH=${HOME}/.local/bin:${PATH}

ENV HC_CONFIG="${HOME}/.config/hipcheck"
#ENTRYPOINT ["/home/hc_user/.local/bin/hc"]
#CMD ["help"]
ENTRYPOINT ["/home/hc_user/.local/bin/scir-oss.sh"]
CMD ["-h"]
