#
# convention use _p_ to shield/protect global vars from main or other plugins
# must be unique from other check names
#

declare -g _p_ANONY_checkname="AnonymousAuthor"

declare -g -a _p_ANONYhits

_p_anony_total_contribs=0

#
# lifecycle main -> involkes init -> -> cache -> run -> report in that order
#
# init: used to structurally integrate plugin check with other check structures
# cache: any caching that may need to occur before run
# run: perform check
# report: report results
#
_p_anony_init()
{
  # P4
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of four
  #   - PFourProjectChecks
  #   - PFourProductChecks
  #   - PFourProtectionChecks
  #   - PFourPolicyChecks
  #
  PFourPolicyChecks[MYscore]+=" ${_p_ANONY_checkname}"

  # CIO
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of six
  #   - CIOlongTermChecks
  #   - CIOdependencyChecks
  #   - CIOsecurityChecks
  #   - CIOintegrityChecks
  #   - CIOmalActorsChecks
  #   - CIOsuitabilityChecks
  #
  CIOlongTermChecks[MYscore]+=" ${_p_ANONY_checkname}"

  # which section of the report results are shown
  # will align with the CIO check above
  #
  # pick on one of six
  #   _LOCAL_SECTION___SECURITY_ID
  #   _LOCAL_SECTION___INTEGRITY_ID
  #   _LOCAL_SECTION___DEPENDENCIES_ID
  #   _LOCAL_SECTION___MALICIOUS_ACTORS_ID
  #   _LOCAL_SECTION___LONG_TERM_SUPPORT_ID
  #   _LOCAL_SECTION___SUITABILITY_ID
  #
  anony_section="${_LOCAL_SECTION___LONG_TERM_SUPPORT_ID}"

  #
  # pick one as to where within the section results
  # the report should appear
  #
  #  among those in the beginning
  #  __REPORT__SECTION__HEAD__
  #  anywhere in the section
  #  __REPORT__SECTION__HERE__
  #  among those at the end
  #  __REPORT__SECTION__TAIL__
  #
  anony_position="${__REPORT__SECTION__TAIL__}"

  #
  # label at it will appear in the CIO summary table
  #
  MYcheckLabels[${_p_ANONY_checkname}]="Anonymous Author"

  MYcheckScores[${_p_ANONY_checkname}]="0"

  MYcheckWeights[${_p_ANONY_checkname}]="${SClow}"

  MYcheckThresholds[${_p_ANONY_checkname}]="0"

  advisoryChecks[${_p_ANONY_checkname}:warn]+="gt"

  #
  # 0 success
  # otherwise failure and plugin will not be run or report
  #
  return 0
}

#
#
# args are:
#  1: "${component}" passed by -C as in 'oparest'
#     this is the prefix for files generally created by OSS-P4/R
#  2: "$(basename "${gh_site}")" basename as in 'opa-restful' as passed by -G as in 'go-training/opa-restful'
#     this is the prefix for cache files from github API and git CLI
#  3: (future reserved)
#  4: (future reserved)
#
_p_anony_run()
{
  local _repo
  local _committer
  local _contribs

  #
  # file generated by the detect_sdn() capability of scir-oss.sh
  #

  _say -n "Counting Anonymous Authors..."

  _contribs="${2}_gitcli_unk_contrib.csv"

  mapfile _p_ANONYhits < <(sed 's:^\([a-zA-Z0-9].*/[a-zA-Z0-9].*\),\(.*\):\2,\1;:' "${_contribs}")

  MYcheckScores[${_p_ANONY_checkname}]="${#_p_ANONYhits[@]}"

  _say "done."
  return 0
}

#
# use echo(1) to return/show values to report
#
_p_anony_report()
{
  local _msg

  _msg=", no anonymous author(s) detected."
  [[ ${MYcheckScores[${_p_ANONY_checkname}]} \
     -gt \
     ${MYcheckThresholds[${_p_ANONY_checkname}]} ]] \
  &&
     _msg=", detected anonymous author(s): $(tr -d '\n' <<<"${ANONYhits[*]}" | sed 's/;$//g')"

  echo "$(\
    _fotp --warnFlag \
      "${MYcheckScores[${_p_ANONY_checkname}]}" \
      "${MYcheckThresholds[${_p_ANONY_checkname}]}" \
      "${advisoryChecks[${_p_ANONY_checkname}:warn]}" \
    )${MYcheckScores[${_p_ANONY_checkname}]}/${MYcheckThresholds[${_p_ANONY_checkname}]}${_msg}"

  return 0
}

#
# plugin interface
#

#
# only loads if specifically set to true (no quotes)
# must match pattern '^[[:space:]]*anony_enabled=true[[:space:]]*$'
#
anony_enabled=true

## associative array of detailed results
anony_results="_p_ANONYhits"

## need to have values for report results
anony_name="Anonymous Author check"
#
# no spaces
anony_id="Anonymous_Author"
anony_label="Anonymous Author(s)"
anony_desc="Contributors that have no identifiable email address"
anony_risk=""

## plugin lifecycle callbacks
anony_init="_p_anony_init"
anony_run="_p_anony_run"
anony_report="_p_anony_report"
