#
# convention use _p_ to shield/protect global vars from main or other plugins
# must be unique from other check names
#

declare -g _p_CUSMX_checkname="CusmxAuthor"

declare -g -A _p_CUSMXhits=()

_p_cusmx_total_contribs=0

#
# lifecycle main -> involkes init -> -> cache -> run -> report in that order
#
# init: used to structurally integrate plugin check with other check structures
# cache: any caching that may need to occur before run
# run: perform check
# report: report results
#
_p_cusmx_init()
{
  # P4
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of four
  #   - PFourProjectChecks
  #   - PFourProductChecks
  #   - PFourProtectionChecks
  #   - PFourPolicyChecks
  #
  PFourProjectChecks[MYscore]+=" ${_p_CUSMX_checkname}"

  # CIO
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of six
  #   - CIOlongTermChecks
  #   - CIOdependencyChecks
  #   - CIOsecurityChecks
  #   - CIOintegrityChecks
  #   - CIOmalActorsChecks
  #   - CIOsuitabilityChecks
  #
  CIOlongTermChecks[MYscore]+=" ${_p_CUSMX_checkname}"

  # which section of the report results are shown
  # will align with the CIO check above
  #
  # pick on one of six
  #   _LOCAL_SECTION___SECURITY_ID
  #   _LOCAL_SECTION___INTEGRITY_ID
  #   _LOCAL_SECTION___DEPENDENCIES_ID
  #   _LOCAL_SECTION___MALICIOUS_ACTORS_ID
  #   _LOCAL_SECTION___LONG_TERM_SUPPORT_ID
  #   _LOCAL_SECTION___SUITABILITY_ID
  #
  cusmx_section="${_LOCAL_SECTION___LONG_TERM_SUPPORT_ID}"

  #
  # label at it will appear in the CIO summary table
  #
  MYcheckLabels[${_p_CUSMX_checkname}]="CUSMX Author"

  MYcheckScores[${_p_CUSMX_checkname}]="0"

  MYcheckWeights[${_p_CUSMX_checkname}]="${SClow}"

  MYcheckThresholds[${_p_CUSMX_checkname}]="0"

  #
  # 0 success
  # otherwise failure and plugin will not be run or report
  #
  return 0
}

#
#
# args are:
#  1: "${component}" passed by -C as in 'oparest'
#     this is the prefix for files generally created by OSS-P4/R
#  2: "$(basename "${gh_site}")" basename as in 'opa-restful' as passed by -G as in 'go-training/opa-restful'
#     this is the prefix for cache files from github API and git CLI
#  3: (future reserved)
#  4: (future reserved)
#
_p_cusmx_run()
{
  local _repo
  local _committer
  local _contribs

  #
  # dependant file _contribs generated by the detect_sdn() capability of scir-oss.sh
  # TODO: devise and add plugin dependency scheme/ordering
  #

  _say -n "Counting CUSMX Authors..."

  cusmx_detailreport="${1}_${_p_CUSMX_checkname}.csv"
  _contribs="${2}_gitcli_contrib.csv"

  echo "\"Country Code\",\"Contributor Email\",\"Project Contributed\"" > "${cusmx_detailreport}"

  while IFS=, read -r _repo _committer
  do
    _p_CUSMXhits["${_repo},${_committer}"]="{ \"committer\":\"${_committer}\", \"repo\": \"${_repo}\" }"
    echo "\"${_committer##*.}\",\"${_committer}\",\"github.com/${_repo}\"" >> "${cusmx_detailreport}"
  done < <(grep -E '(\.ca$|\.com$|\.edu$|\.mx$)' < "${_contribs}")

  MYcheckScores[${_p_CUSMX_checkname}]="${#_p_CUSMXhits[@]}"
  _p_cusmx_total_contribs="$(sort < "${_contribs}" | uniq | wc -l)"

  _say "done."
  return 0
}

#
# use echo(1) to return/show values to report
#
_p_cusmx_report()
{
  local _msg
  local _count_ca
  local _count_com
  local _count_edu
  local _count_mx
  local _t

  _count_ca=0
  _count_com=0
  _count_edu=0
  _count_mx=0

  for _t in 'ca' 'com' 'edu' 'mx'
  do
    unset -n _c; local -n _c; _c=_count_${_t}
    _c=0
    for key in "${!_p_CUSMXhits[@]}"; do
      [[ "${key}" =~ ".${_t}"$ ]] && (( _c++ ))
    done
  done

  _msg=", no CUSMX author(s) detected."
  _t=$(( _count_ca + _count_com + _count_edu + _count_mx ))
  [[ ${_t} \
     -gt \
     ${MYcheckThresholds[${_p_CUSMX_checkname}]} ]] \
  && \
     _msg=", detected author(s) from CA=${_count_ca}, COM=${_count_com}, EDU=${_count_edu}, and MX=${_count_mx} which comprise $(printf "%.3f%% of all %'.0f contributors" $(echo "${_t}/${_p_cusmx_total_contribs}*100" | bc -l) "${_p_cusmx_total_contribs}")"

# details if needed someday
#  [[ ${MYcheckScores[${_p_CUSMX_checkname}]} -gt ${MYcheckThresholds[${_p_CUSMX_checkname}]} ]] && _msg=", detected anonymous author(s) $( jq -r '.|[.committer, .repo]|join(",")' <<<"${_p_CUSMXhits[@]}"|tr '\n' ';'|sed 's/;/; /g'|sed 's/; $//g' )"

  echo "$(\
    _fotp \
      "${MYcheckScores[${_p_CUSMX_checkname}]}" \
      "${MYcheckThresholds[${_p_CUSMX_checkname}]}" \
      "gt" \
    )${MYcheckScores[${_p_CUSMX_checkname}]}/${MYcheckThresholds[${_p_CUSMX_checkname}]}${_msg}"

  return 0
}

#
# plugin interface
#

#
# only loads if specifically set to true (no quotes)
# must match pattern '^[[:space:]]*crink_enabled=true[[:space:]]*$'
#
cusmx_enabled=false

## associative array of detailed results
cusmx_results="_p_CUSMXhits"
## if any detailed results in a file
## name is set here in _run fn
cusmx_detailreport=""

## need to have values for report results
cusmx_name="Canada, US, Mexico check"
cusmx_id="CUSMX_Author"
cusmx_label="CUSMX Author(s)"
cusmx_desc="Contributors with email identifing with .ca, .us, or .mx domains"
cusmx_risk=""

## plugin lifecycle callbacks
cusmx_init="_p_cusmx_init"
cusmx_run="_p_cusmx_run"
cusmx_report="_p_cusmx_report"
