#
# convention use _p_ to shield/protect global vars from main or other plugins
# must be unique from other check names
#

declare -g _p_PREPORT_checkname="ProblemReporting"

declare -g -a _p_PREPORThits

_p_pReport_total_openIssues=0

#
# lifecycle main -> involkes init -> -> cache -> run -> report in that order
#
# init: used to structurally integrate plugin check with other check structures
# cache: any caching that may need to occur before run
# run: perform check
# report: report results
#
_p_pReport_init()
{
  # P4
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of four
  #   - PFourProjectChecks
  #   - PFourProductChecks
  #   - PFourProtectionChecks
  #   - PFourPolicyChecks
  #
  PFourProjectChecks[MYscore]+=" ${_p_PREPORT_checkname}"

  # CIO
  # required (defines where scores are consolidated):
  # register check name under MYscore checks, pick one of six
  #   - CIOlongTermChecks
  #   - CIOdependencyChecks
  #   - CIOsecurityChecks
  #   - CIOintegrityChecks
  #   - CIOmalActorsChecks
  #   - CIOsuitabilityChecks
  #
  CIOlongTermChecks[MYscore]+=" ${_p_PREPORT_checkname}"

  # which section of the report results are shown
  # will align with the CIO check above
  #
  # pick one of six
  #   _LOCAL_SECTION___SECURITY_ID
  #   _LOCAL_SECTION___INTEGRITY_ID
  #   _LOCAL_SECTION___DEPENDENCIES_ID
  #   _LOCAL_SECTION___MALICIOUS_ACTORS_ID
  #   _LOCAL_SECTION___LONG_TERM_SUPPORT_ID
  #   _LOCAL_SECTION___SUITABILITY_ID
  #
  pReport_section="${_LOCAL_SECTION___LONG_TERM_SUPPORT_ID}"

  #
  # pick one as to where within the section results
  # the report should appear
  #
  #  among those in the beginning
  #  __REPORT__SECTION__HEAD__
  #  anywhere in the section
  #  __REPORT__SECTION__HERE__
  #  among those at the end
  #  __REPORT__SECTION__TAIL__
  #
  pReport_position="${__REPORT__SECTION__HERE__}"

  #
  # label at it will appear in the CIO summary table
  #
  MYcheckLabels[${_p_PREPORT_checkname}]="Problem Reporting"

  MYcheckScores[${_p_PREPORT_checkname}]="false"

  MYcheckWeights[${_p_PREPORT_checkname}]="${SCcritical}"

  MYcheckThresholds[${_p_PREPORT_checkname}]="true"

  #
  # 0 success
  # otherwise failure and plugin will not be run or report
  #
  return 0
}

#
#
# args are:
#  1: "${component}" passed by -C as in 'oparest'
#     this is the prefix for files generally created by OSS-P4/R
#  2: "$(basename "${gh_site}")" basename as in 'opa-restful' as passed by -G as in 'go-training/opa-restful'
#     this is the prefix for cache files from github API and git CLI
#  3: (future reserved)
#  4: (future reserved)
#
_p_pReport_run()
{
  local _repo
  local _committer
  local _ghapijson

  #
  # file generated by the detect_sdn() capability of scir-oss.sh
  #

  _say -n "Detecting Problem Reporting Process..."

  _ghapijson="${2}_ghapi.json"

  MYcheckScores[${_p_PREPORT_checkname}]="$(jq -rj '.has_issues' "${_ghapijson}")"
  _p_pReport_total_openIssues="$(jq -rj '.open_issues' "${_ghapijson}")"


  _say "done."
  return 0
}

#
# use echo(1) to return/show values to report
#
_p_pReport_report()
{
  local _msg

  _msg="$( \
    sed 's/"//g;s/\t/ /g;s/TRUE/Yes/gi' \
      < <(echo \
    "${MYcheckScores[${_p_PREPORT_checkname}]} with ${_p_pReport_total_openIssues} open issues" \
         ) \
  )"
  if ! echo "${_msg}" | grep -q -E "(^Yes)"; then _msg="${__REDFLAG__}${_msg}"; fi

  echo "${_msg//false/None}"

  return 0
}

#
# plugin interface
#

#
# only loads if specifically set to true (no quotes)
# must match pattern '^[[:space:]]*pReport_enabled=true[[:space:]]*$'
#
pReport_enabled=true

## associative array of detailed results
pReport_results="_p_PREPORThits"

## need to have values for report results
pReport_name="Problem Reporting Process check"
#
# no spaces
pReport_id="Problem_Reporting_Process"
pReport_label="Problem Reporting Process"
pReport_desc="Whether maintainers have a published process for reporting problems"
pReport_risk=""

## plugin lifecycle callbacks
pReport_init="_p_pReport_init"
pReport_run="_p_pReport_run"
pReport_report="_p_pReport_report"
